version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ddisson/kitty_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media  # Assuming this is where media files are stored in your Django app

  frontend:
    env_file: .env
    image: ddisson/kitty_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: ddisson/kitty_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles
      - media:/app/media
